# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.2
  - 7.1
  - 7.0

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common python-software-properties
  - LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
  - sudo apt-get install -y php-ast

# Commands to be run before your environment runs.
before_script:

# Commands you want to run that will verify your build.
script: 
  - rm composer.lock
  - composer install
  - composer require php-coveralls/php-coveralls
  - mkdir -p build/logs
  - vendor/bin/phpunit
  - vendor/bin/phan -o phan-analysis.log -m json
  - tail phan-analysis.log

# Execute another command after success of the script.
after_success:
  - vendor/bin/php-coveralls -v

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always
